export const fbVideos = [
  {
    id: "01",
    src: "/media/fb/01.mp4",
    poster: "/media/fb/01.jpg",
    caption: "DUH, my sister!",
    href: "https://www.facebook.com/share/r/1BzgNVb2g3/",
  },
  {
    id: "02",
    src: "/media/fb/02.mp4",
    poster: "/media/fb/02.jpg",
    caption: "A reel from The League Haircuts. Tagged barbershop, humor, Chester County, and Exton.",
    href: "https://www.facebook.com/share/r/19mMjY9ind/",
  },
  {
    id: "03",
    src: "/media/fb/03.mp4",
    poster: "/media/fb/03.jpg",
    caption: "If you\u2019re not leaving the barbershop with Alex\u2019s confidence, then what are you even doing",
    href: "https://www.facebook.com/share/r/19UKgLn6Vm/",
  },
  {
    id: "04",
    src: "/media/fb/04.mp4",
    poster: "/media/fb/04.jpg",
    caption: "Fun facts about Jessica you probably didn\u2019t know!",
    href: "https://www.facebook.com/share/r/1DFfqxg4d8/",
  },
  {
    id: "05",
    src: "/media/fb/05.mp4",
    poster: "/media/fb/05.jpg",
    caption: "All in good fun \ud83e\udd2d",
    href: "https://www.facebook.com/share/r/19bV5Hwg2T/",
  },
  {
    id: "06",
    src: "/media/fb/06.mp4",
    poster: "/media/fb/06.jpg",
    caption: "Those clippers sound like they\u2019re 3000 miles overdue for some oil \ud83d\ude05",
    href: "https://www.facebook.com/share/r/1Dc6LjfhjU/",
  },
  {
    id: "07",
    src: "/media/fb/07.mp4",
    poster: "/media/fb/07.jpg",
    caption: "A true client testimonial \ud83d\udcaf",
    href: "https://www.facebook.com/share/r/197bsosG3R/",
  },
  {
    id: "08",
    src: "/media/fb/08.mp4",
    poster: "/media/fb/08.jpg",
    caption: "These two studs OBVIOUSLY loved their experience with @best_cut_secret \ud83e\udd29",
    href: "https://www.facebook.com/share/r/1CDiVyzzay/",
  },
  {
    id: "09",
    src: "/media/fb/09.mp4",
    poster: "/media/fb/09.jpg",
    caption: "Episode 2 featuring the USA spelling bee champion \ud83d\udc1d with a new sponsor this week!",
    href: "https://www.facebook.com/share/r/19QqadPq5S/",
  },
  {
    id: "10",
    src: "/media/fb/10.mp4",
    poster: "/media/fb/10.jpg",
    caption: "Episode 2 featuring the USA spelling bee champion \ud83d\udc1d with a new sponsor this week!",
    href: "https://www.facebook.com/share/r/1DhaUqsiyz/",
  },
  {
    id: "11",
    src: "/media/fb/11.mp4",
    poster: "/media/fb/11.jpg",
    caption: "Hannah who? \ud83e\udd14 Give the people what they want!! LIZZIE MCGUIRE REUNION MOVIE @hilaryduff",
    href: "https://www.facebook.com/share/r/1D1AbmmKxX/",
  },
  {
    id: "12",
    src: "/media/fb/12.mp4",
    poster: "/media/fb/12.jpg",
    caption: "Come check us out to see what all the buzz is about \u2b50\ufe0f \u2b50\ufe0f \u2b50\ufe0f \u2b50\ufe0f \u2b50\ufe0f",
    href: "https://www.facebook.com/share/r/1T4E8vUmgH/",
  },
  {
    id: "13",
    src: "/media/fb/13.mp4",
    poster: "/media/fb/13.jpg",
    caption: "Lead-off hitter, Hudson, for our new \u201ckids against humanity\u201d segment. Knocked it out of the park with those answers \u26be\ufe0f",
    href: "https://www.facebook.com/share/r/1GafLiqXTF/",
  },
  {
    id: "14",
    src: "/media/fb/14.mp4",
    poster: "/media/fb/14.jpg",
    caption: "Getting into character \ud83e\udd29",
    href: "https://www.facebook.com/share/r/1HkRHGZYkX/",
  },
  {
    id: "15",
    src: "/media/fb/15.mp4",
    poster: "/media/fb/15.jpg",
    caption: "Lead-off hitter, Hudson, for our new \u201ckids against humanity\u201d segment. Knocked it out of the park with those answers \u26be\ufe0f",
    href: "https://www.facebook.com/share/r/1KbWMwZWkD/",
  },
  {
    id: "16",
    src: "/media/fb/16.mp4",
    poster: "/media/fb/16.jpg",
    caption: "3..2..1.. \ud83c\udfac some LIVE action for ya\u2019ll today \ud83c\udfa4",
    href: "https://www.facebook.com/share/r/1CK6ycPF5h/",
  },
  {
    id: "17",
    src: "/media/fb/17.mp4",
    poster: "/media/fb/17.jpg",
    caption: "From sleeping through cuts to doing them \u2705 mention \u201cbook with beezer\u201d for a complimentary high five during your next visit \u270b\ud83c\udffc",
    href: "https://www.facebook.com/share/r/1CktvrALk7/",
  },
  {
    id: "18",
    src: "/media/fb/18.mp4",
    poster: "/media/fb/18.jpg",
    caption: "Got her. Hook, line, and sinker \ud83c\udfa3 \ud83e\udd21",
    href: "https://www.facebook.com/share/r/1BxaxHiBiB/",
  },
  {
    id: "19",
    src: "/media/fb/19.mp4",
    poster: "/media/fb/19.jpg",
    caption: "It\u2019s a surpriseeee \ud83e\udd2b\ud83e\udd2b\ud83e\udd2b",
    href: "https://www.facebook.com/share/r/1SEZ2FKaxS/",
  },
  {
    id: "20",
    src: "/media/fb/20.mp4",
    poster: "/media/fb/20.jpg",
    caption: "A reel from The League Haircuts. Tagged barbershop, Exton PA, and girl barber.",
    href: "https://www.facebook.com/share/r/1FNMVfvKnY/",
  },
  {
    id: "21",
    src: "/media/fb/21.mp4",
    poster: "/media/fb/21.jpg",
    caption: "It\u2019s a surpriseeee \ud83e\udd2b\ud83e\udd2b\ud83e\udd2b",
    href: "https://www.facebook.com/share/r/1861kRgnjg/",
  },
  {
    id: "22",
    src: "/media/fb/22.mp4",
    poster: "/media/fb/22.jpg",
    caption: "A reel from The League Haircuts. Tagged barbershop, Exton PA, and girl barber.",
    href: "https://www.facebook.com/share/r/1Eke3zMxUx/",
  },
  {
    id: "23",
    src: "/media/fb/23.mp4",
    poster: "/media/fb/23.jpg",
    caption: "A reel from The League Haircuts. Tagged barbershop, Exton PA, and girl barber.",
    href: "https://www.facebook.com/share/r/19F83Lt7uT/",
  },
] as const;
