/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as GoogleReviewsRouteImport } from './routes/google-reviews'
import { Route as NowHiringRouteImport } from './routes/now-hiring'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VagaroReviewsRouteImport } from './routes/vagaro-reviews'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleReviewsRoute = GoogleReviewsRouteImport.update({
  id: '/google-reviews',
  path: '/google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const NowHiringRoute = NowHiringRouteImport.update({
  id: '/now-hiring',
  path: '/now-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VagaroReviewsRoute = VagaroReviewsRouteImport.update({
  id: '/vagaro-reviews',
  path: '/vagaro-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/now-hiring': typeof NowHiringRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vagaro-reviews': typeof VagaroReviewsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/now-hiring': typeof NowHiringRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vagaro-reviews': typeof VagaroReviewsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/google-reviews': typeof GoogleReviewsRoute
  '/now-hiring': typeof NowHiringRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vagaro-reviews': typeof VagaroReviewsRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/gallery'
    | '/gift-cards'
    | '/google-reviews'
    | '/now-hiring'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/team'
    | '/terms'
    | '/vagaro-reviews'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/gallery'
    | '/gift-cards'
    | '/google-reviews'
    | '/now-hiring'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/team'
    | '/terms'
    | '/vagaro-reviews'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/gallery'
    | '/gift-cards'
    | '/google-reviews'
    | '/now-hiring'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/team'
    | '/terms'
    | '/vagaro-reviews'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GiftCardsRoute: typeof GiftCardsRoute
  GoogleReviewsRoute: typeof GoogleReviewsRoute
  NowHiringRoute: typeof NowHiringRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VagaroReviewsRoute: typeof VagaroReviewsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-reviews': {
      id: '/google-reviews'
      path: '/google-reviews'
      fullPath: '/google-reviews'
      preLoaderRoute: typeof GoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-hiring': {
      id: '/now-hiring'
      path: '/now-hiring'
      fullPath: '/now-hiring'
      preLoaderRoute: typeof NowHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagaro-reviews': {
      id: '/vagaro-reviews'
      path: '/vagaro-reviews'
      fullPath: '/vagaro-reviews'
      preLoaderRoute: typeof VagaroReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GiftCardsRoute: GiftCardsRoute,
  GoogleReviewsRoute: GoogleReviewsRoute,
  NowHiringRoute: NowHiringRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VagaroReviewsRoute: VagaroReviewsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
